version: "3.7"
services:
    hive:
        build: .
        image: hive/condenser:latest
        container_name: hive
        environment:
            VIRTUAL_HOST: hivean.com
            VIRTUAL_PORT: 8080
            DISABLE_CLUSTERING: true
            SDC_CLIENT_STEEMD_URL: https://api.hive.blog
            SDC_SERVER_STEEMD_URL: https://api.hive.blog
            SDC_DISABLE_SIGNUPS: 1
            SDC_SITE_DOMAIN: hivean.com
            SDC_IMAGE_PROXY_PREFIX: https://images.hive.blog/
            SDC_UPLOAD_IMAGE_URL: https://images.hive.blog
            SDC_HELMET_CONNECTSRC: "'self' steemit.com https://api.hive.blog https://hivean.com https://images.hive.blog"
            WALLET_URL: https://wallet.hivean.com
        networks:
            - proxy_reverse-proxy
        restart: always

networks:
    proxy_reverse-proxy:
        external:
            name: proxy_reverse-proxy
